### ISSUE TITLE
Regex scanner doesn't allow scanning files with a second '.' in the file extension/name

### ISSUE THREAD

**Issue by eheyhuron** [forcedotcom/code-analyzer-translator#284]
See: [code-analyzer-regex-engine/src/config.ts](https://github.com/forcedotcom/code-analyzer-core/blob/9f57613082b24c80afdb9660afe09cc6172fbc5b/packages/code-analyzer-regex-engine/src/config.ts#L59)

Using the following config:
```
engines:
  regex:
      "NoRecordIDs":
            regex: '/\b[a-z0-9]\w{4}0\w{9}(\w{3})?\b/g'
            file_extensions: [".apex", ".cls", ".trigger", ".js", ".email", ".flow-meta.xml", ".md-meta.xml", ".field-meta.xml", ".webLink-meta.xml", ".validationRule-meta.xml"]
            description: "Prevents hard-coded record IDs comments from being used."
            violation_message: "A hard-coded Salesforce RecordID was present in your code or configuration. Please replace with a deployment-safe alternative. See https://admin.salesforce.com/blog/2021/why-you-should-avoid-hard-coding-and-three-alternative-solutions"
            severity: "Moderate"
            tags: 
              - TechDebt
              - BestPractices

```

Throws this error:
```
Error: Core [11:19:17]: Failed to create engine with name 'regex' due to the following error:
 »   The 'engines.regex.custom_rules.NoRecordIDs.file_extensions[3]' configuration value is invalid. The string did not match the regular expression pattern: /^[.][a-zA-Z0-9]+$/  
```

Changing file_extensions to 
`file_extensions: [".apex", ".cls", ".trigger", ".js", ".email"]`
removes the error.
